# Generated by Django 5.2.7 on 2025-10-13 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTelegram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_id",
                    models.CharField(
                        help_text="Укажите chat_id телеграм пользователя",
                        max_length=32,
                        unique=True,
                        verbose_name="Chat_id телеграм пользователя",
                    ),
                ),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True,
                        help_text="Укажите username телеграм пользователя",
                        max_length=64,
                        null=True,
                        verbose_name="Username телеграм пользователя",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Укажите пользователя",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь - владелец привычки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Чат id телеграм",
                "verbose_name_plural": "Чаты id телеграм",
            },
        ),
    ]
