# Generated by Django 5.2.7 on 2025-10-12 16:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Укажите действие",
                        max_length=255,
                        verbose_name="Действие - что делать",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Укажите время, в которое выполняется привычка",
                        verbose_name="Время выполнения привычки",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Укажите место выполнения",
                        max_length=255,
                        verbose_name="Место выполнения привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Укажите периодичность выполнения привычки в днях (минимум 1, максимум 7)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                        verbose_name="Периодичность выполнения привычки",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Укажите вознаграждение за выполнение привычки",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение за выполнение привычки",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Сделайте выбор привычки",
                        verbose_name="Признак, что привычка является приятной (а не полезной)",
                    ),
                ),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        help_text="Длительность в секундах, максимум 120",
                        validators=[django.core.validators.MaxValueValidator(120)],
                        verbose_name="Время на выполнение привычки",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Сделайте выбор признака публичности привычки",
                        verbose_name="Признак публичности привычки (доступна другим пользователям для просмотра)",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Сделайте выбор привычки",
                        limit_choices_to={"is_pleasant": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pleasant_habits",
                        to="habits.habit",
                        verbose_name="Связанная приятная привычка (только приятные можно выбирать)",
                    ),
                ),
            ],
        ),
    ]
