# Generated by Django 5.2.7 on 2025-10-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_reminded_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Время напоминания о выполнении привычки, осуществленное в последний раз",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="remind_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Введите время напоминания о выполнении привычки",
                null=True,
                verbose_name="Время напоминания о выполнении привычки",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="repeat",
            field=models.CharField(
                choices=[
                    ("none", "Один раз"),
                    ("daily", "Ежедневно"),
                    ("weekly", "Еженедельно"),
                ],
                default="none",
                help_text="Сделайте выбор режима повторения привычки",
                max_length=20,
                verbose_name="Режим повторения привычки",
            ),
        ),
    ]
